# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-06 05:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResPartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=200, unique=True, verbose_name='Email')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Image')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('password', models.CharField(max_length=200, verbose_name='Password')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Address2')),
                ('is_company', models.BooleanField(default=False, verbose_name='Company')),
                ('vat_number', models.CharField(blank=True, max_length=200, verbose_name='Vat Number')),
                ('parent', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Customers.ResPartner')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
