# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-06 07:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0004_auto_20180406_0625'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordernumber', models.CharField(max_length=50, verbose_name='Name')),
                ('total', models.FloatField(verbose_name='Total')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customers.ResPartner', verbose_name='Customer')),
            ],
        ),
        migrations.CreateModel(
            name='SaleOrderLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_price', models.FloatField(verbose_name='Price')),
                ('qty', models.IntegerField(verbose_name='Quantity')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customers.ProductProduct', verbose_name='Product')),
                ('saleorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customers.SaleOrder', verbose_name='Sale Order')),
            ],
        ),
    ]
