# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-06 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0005_saleorder_saleorderline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleorder',
            name='total',
            field=models.FloatField(blank=True, verbose_name='Total'),
        ),
    ]
