# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-06 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0006_auto_20180406_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleorderline',
            name='product_price',
            field=models.FloatField(default=1.0, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='saleorderline',
            name='qty',
            field=models.IntegerField(default=1, verbose_name='Quantity'),
        ),
    ]
